--- #YAML:1.0
name:                InlineX-XS
version:             0.01
abstract:            Auto-convert Inline::C based modules to XS
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Müller <smueller@cpan.org>
